# Generated by Django 5.1.1 on 2024-10-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_alter_telegramuser_telegram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='username',
        ),
    ]
