# Generated by Django 5.1.1 on 2024-10-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_remove_telegramuser_telegram_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
