# Generated by Django 5.1.1 on 2024-10-23 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_alter_telegramuser_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='telegramuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
